### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by robdy** [d0n601/ryankozak.com#1]
Hi Ryan,
Looks like [search page](https://ryankozak.com/search.html) on your blog is not working properly.

If I search for `test` it redirects me to: 
```
https://www.google.com/search?q=test&sitesearch=localhost%3A4000
```
(notice `localhost%3A4000`)

**Comment by d0n601** [comment]
Thanks for taking the time to create an issue and point this out to me! I really appreciate it, and went a head and fixed it up https://github.com/d0n601/ryankozak.com/commit/9eeb2851fbf5118629df3d716aa9abe607d2fa80#diff-0dc5c629ea211081948fcdbb1a959a89

Thanks again!

**Comment by robdy** [comment]
Confirmed :+1:
